In [1]:
faqs = """About the Program

What is the Course fee for Data Science Mentorship Program (DSMP 2023)?
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.

What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600 (approx.)

What is the syllabus of the mentorship program?
We will be covering the following modules:
- Python Fundamentals
- Python libraries for Data Science
- Data Analysis
- SQL for Data Science
- Maths for Machine Learning
- ML Algorithms
- Practical ML
- MLOps
- Case studies

You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program
"""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
tokenizer.fit_on_texts([faqs])

In [4]:
tokenizer.word_index

{'the': 1,
 'course': 2,
 'data': 3,
 'program': 4,
 'is': 5,
 'for': 6,
 'science': 7,
 'of': 8,
 'what': 9,
 'mentorship': 10,
 'total': 11,
 'fee': 12,
 'monthly': 13,
 'you': 14,
 'rs': 15,
 '799': 16,
 'duration': 17,
 '7': 18,
 'syllabus': 19,
 'python': 20,
 'ml': 21,
 'campusx': 22,
 'about': 23,
 'dsmp': 24,
 '2023': 25,
 'follows': 26,
 'a': 27,
 'subscription': 28,
 'model': 29,
 'where': 30,
 'have': 31,
 'to': 32,
 'make': 33,
 'payments': 34,
 'month': 35,
 'months': 36,
 'so': 37,
 'becomes': 38,
 '5600': 39,
 'approx': 40,
 'we': 41,
 'will': 42,
 'be': 43,
 'covering': 44,
 'following': 45,
 'modules': 46,
 'fundamentals': 47,
 'libraries': 48,
 'analysis': 49,
 'sql': 50,
 'maths': 51,
 'machine': 52,
 'learning': 53,
 'algorithms': 54,
 'practical': 55,
 'mlops': 56,
 'case': 57,
 'studies': 58,
 'can': 59,
 'check': 60,
 'detailed': 61,
 'here': 62,
 'https': 63,
 'learnwith': 64,
 'in': 65,
 'courses': 66}

In [20]:
for sentence in faqs.split('\n'):
  t_sen=tokenizer.texts_to_sequences([sentence])[0]
  print(t_sen)

[23, 1, 4]
[]
[9, 5, 1, 2, 12, 6, 3, 7, 10, 4, 24, 25]
[1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34, 8, 15, 16, 35]
[]
[9, 5, 1, 11, 17, 8, 1, 2]
[1, 11, 17, 8, 1, 2, 5, 18, 36, 37, 1, 11, 2, 12, 38, 16, 18, 15, 39, 40]
[]
[9, 5, 1, 19, 8, 1, 10, 4]
[41, 42, 43, 44, 1, 45, 46]
[20, 47]
[20, 48, 6, 3, 7]
[3, 49]
[50, 6, 3, 7]
[51, 6, 52, 53]
[21, 54]
[55, 21]
[56]
[57, 58]
[]
[14, 59, 60, 1, 61, 19, 62, 63, 64, 22, 65, 66, 22, 3, 7, 10, 4]
[]


In [13]:
input_sequences=[]
for sentence in faqs.split('\n'):
  t_sen=tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1,len(t_sen)):
    n_gram = t_sen[:i+1]
    input_sequences.append(n_gram)
input_sequences

[[23, 1],
 [23, 1, 4],
 [9, 5],
 [9, 5, 1],
 [9, 5, 1, 2],
 [9, 5, 1, 2, 12],
 [9, 5, 1, 2, 12, 6],
 [9, 5, 1, 2, 12, 6, 3],
 [9, 5, 1, 2, 12, 6, 3, 7],
 [9, 5, 1, 2, 12, 6, 3, 7, 10],
 [9, 5, 1, 2, 12, 6, 3, 7, 10, 4],
 [9, 5, 1, 2, 12, 6, 3, 7, 10, 4, 24],
 [9, 5, 1, 2, 12, 6, 3, 7, 10, 4, 24, 25],
 [1, 2],
 [1, 2, 26],
 [1, 2, 26, 27],
 [1, 2, 26, 27, 13],
 [1, 2, 26, 27, 13, 28],
 [1, 2, 26, 27, 13, 28, 29],
 [1, 2, 26, 27, 13, 28, 29, 30],
 [1, 2, 26, 27, 13, 28, 29, 30, 14],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34, 8],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34, 8, 15],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34, 8, 15, 16],
 [1, 2, 26, 27, 13, 28, 29, 30, 14, 31, 32, 33, 13, 34, 8, 15, 16, 35],
 [9, 

In [24]:
max_len=max([len(x) for x in input_sequences])
max_len

20

In [50]:
from tensorflow.keras.utils import pad_sequences
padded_seq=pad_sequences(input_sequences,padding='pre',maxlen=max_len)
padded_seq

array([[ 0,  0,  0, ...,  0, 23,  1],
       [ 0,  0,  0, ..., 23,  1,  4],
       [ 0,  0,  0, ...,  0,  9,  5],
       ...,
       [ 0,  0,  0, ..., 22,  3,  7],
       [ 0,  0,  0, ...,  3,  7, 10],
       [ 0,  0,  0, ...,  7, 10,  4]], dtype=int32)

In [51]:
x=padded_seq[:,:-1]
x

array([[ 0,  0,  0, ...,  0,  0, 23],
       [ 0,  0,  0, ...,  0, 23,  1],
       [ 0,  0,  0, ...,  0,  0,  9],
       ...,
       [ 0,  0,  0, ..., 66, 22,  3],
       [ 0,  0,  0, ..., 22,  3,  7],
       [ 0,  0,  0, ...,  3,  7, 10]], dtype=int32)

In [52]:
y=padded_seq[:,-1]
y

array([ 1,  4,  5,  1,  2, 12,  6,  3,  7, 10,  4, 24, 25,  2, 26, 27, 13,
       28, 29, 30, 14, 31, 32, 33, 13, 34,  8, 15, 16, 35,  5,  1, 11, 17,
        8,  1,  2, 11, 17,  8,  1,  2,  5, 18, 36, 37,  1, 11,  2, 12, 38,
       16, 18, 15, 39, 40,  5,  1, 19,  8,  1, 10,  4, 42, 43, 44,  1, 45,
       46, 47, 48,  6,  3,  7, 49,  6,  3,  7,  6, 52, 53, 54, 21, 58, 59,
       60,  1, 61, 19, 62, 63, 64, 22, 65, 66, 22,  3,  7, 10,  4],
      dtype=int32)

In [53]:
x.shape

(100, 19)

In [54]:
y.shape

(100,)

In [55]:
len(tokenizer.word_index)

66

In [56]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=67)

In [57]:
y.shape

(100, 67)

In [58]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [66]:
model=Sequential()
model.add(Embedding(282,100,input_length=19)) #vocabulary count,output dense vector, input length
model.add(LSTM(150)) # 150 nodes
model.add(Dense(67,activation='softmax')) # vocabulary count
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) # because it is a multiclass classification problem.
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 19, 100)           28200     
                                                                 
 lstm_4 (LSTM)               (None, 150)               150600    
                                                                 
 dense_4 (Dense)             (None, 67)                10117     
                                                                 
Total params: 188917 (737.96 KB)
Trainable params: 188917 (737.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [67]:
# embedding layer convert the sparse vector into dense vector (1,56,100) for each word, there are 100 numbers.

In [68]:
model.fit(x,y,epochs=100)

Epoch 1/100
4/4 [==============================] - 3s 38ms/step - loss: 4.2028 - accuracy: 0.0200
Epoch 2/100
4/4 [==============================] - 0s 28ms/step - loss: 4.1741 - accuracy: 0.0800
Epoch 3/100
4/4 [==============================] - 0s 35ms/step - loss: 4.1327 - accuracy: 0.1100
Epoch 4/100
4/4 [==============================] - 0s 29ms/step - loss: 4.0154 - accuracy: 0.1000
Epoch 5/100
4/4 [==============================] - 0s 31ms/step - loss: 3.9076 - accuracy: 0.1000
Epoch 6/100
4/4 [==============================] - 0s 31ms/step - loss: 3.8513 - accuracy: 0.1000
Epoch 7/100
4/4 [==============================] - 0s 38ms/step - loss: 3.8152 - accuracy: 0.1100
Epoch 8/100
4/4 [==============================] - 0s 35ms/step - loss: 3.7928 - accuracy: 0.1200
Epoch 9/100
4/4 [==============================] - 0s 36ms/step - loss: 3.7692 - accuracy: 0.1000
Epoch 10/100
4/4 [==============================] - 0s 30ms/step - loss: 3.7406 - accuracy: 0.1100
Epoch 11/100
4/4 [=

In [74]:
text='Maths'
# tokenize
token_text=tokenizer.texts_to_sequences([text])[0]
# padding
padded_token=pad_sequences([token_text],maxlen=19,padding='pre')
# predict
model.predict(padded_token)

1/1 [==============================] - 0s 449ms/step


array([[4.82764517e-05, 2.44229613e-03, 1.81609695e-03, 3.14449333e-03,
        3.29887669e-04, 1.31301116e-02, 7.44202554e-01, 7.81112525e-04,
        1.39626488e-03, 3.08689778e-05, 3.37988633e-04, 5.35674300e-03,
        3.69828753e-03, 2.55865254e-03, 1.15609575e-04, 2.45037263e-05,
        1.27898093e-04, 1.13927817e-03, 2.18945512e-04, 3.14498367e-03,
        4.95488639e-05, 1.82369798e-02, 6.92183501e-04, 2.61334317e-05,
        4.95770801e-05, 3.09929892e-05, 1.09492242e-02, 9.43179335e-03,
        3.81788966e-04, 1.53394751e-04, 9.17295038e-05, 2.03889009e-04,
        9.20049497e-05, 4.93283005e-05, 8.36373511e-05, 2.36708092e-06,
        8.31615689e-05, 3.08626535e-04, 1.84292745e-04, 6.31807552e-06,
        3.86076272e-06, 2.89803374e-05, 8.11336748e-03, 1.74242246e-03,
        2.25501601e-03, 3.62902414e-04, 3.30197247e-04, 2.51853820e-02,
        2.12956350e-02, 9.57928505e-03, 3.49630609e-05, 4.33399473e-05,
        1.07852668e-02, 5.95092960e-03, 2.55926698e-02, 4.675336

In [78]:
import numpy as np
pos=np.argmax(model.predict(padded_token))
for word,index in tokenizer.word_index.items():
  if index==pos:
    print(word)

1/1 [==============================] - 0s 41ms/step
for


In [77]:
tokenizer.word_index

{'the': 1,
 'course': 2,
 'data': 3,
 'program': 4,
 'is': 5,
 'for': 6,
 'science': 7,
 'of': 8,
 'what': 9,
 'mentorship': 10,
 'total': 11,
 'fee': 12,
 'monthly': 13,
 'you': 14,
 'rs': 15,
 '799': 16,
 'duration': 17,
 '7': 18,
 'syllabus': 19,
 'python': 20,
 'ml': 21,
 'campusx': 22,
 'about': 23,
 'dsmp': 24,
 '2023': 25,
 'follows': 26,
 'a': 27,
 'subscription': 28,
 'model': 29,
 'where': 30,
 'have': 31,
 'to': 32,
 'make': 33,
 'payments': 34,
 'month': 35,
 'months': 36,
 'so': 37,
 'becomes': 38,
 '5600': 39,
 'approx': 40,
 'we': 41,
 'will': 42,
 'be': 43,
 'covering': 44,
 'following': 45,
 'modules': 46,
 'fundamentals': 47,
 'libraries': 48,
 'analysis': 49,
 'sql': 50,
 'maths': 51,
 'machine': 52,
 'learning': 53,
 'algorithms': 54,
 'practical': 55,
 'mlops': 56,
 'case': 57,
 'studies': 58,
 'can': 59,
 'check': 60,
 'detailed': 61,
 'here': 62,
 'https': 63,
 'learnwith': 64,
 'in': 65,
 'courses': 66}

In [81]:
text='Maths'
for i in range(3):
  # tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token=pad_sequences([token_text],maxlen=19,padding='pre')
  # predict
  model.predict(padded_token)
  pos=np.argmax(model.predict(padded_token))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+' '+word
      print(text)

1/1 [==============================] - 0s 35ms/step
Maths for
1/1 [==============================] - 0s 38ms/step
Maths for machine
1/1 [==============================] - 0s 35ms/step
Maths for machine learning


In [86]:
text='we are going'
for i in range(10):
  # tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token=pad_sequences([token_text],maxlen=19,padding='pre')
  # predict
  model.predict(padded_token)
  pos=np.argmax(model.predict(padded_token))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+' '+word
      print(text)

1/1 [==============================] - 0s 27ms/step
we are going will
1/1 [==============================] - 0s 29ms/step
we are going will be
1/1 [==============================] - 0s 27ms/step
we are going will be covering
1/1 [==============================] - 0s 24ms/step
we are going will be covering the
1/1 [==============================] - 0s 26ms/step
we are going will be covering the following
1/1 [==============================] - 0s 25ms/step
we are going will be covering the following modules
1/1 [==============================] - 0s 25ms/step
we are going will be covering the following modules modules
1/1 [==============================] - 0s 25ms/step
we are going will be covering the following modules modules modules
1/1 [==============================] - 0s 29ms/step
we are going will be covering the following modules modules modules learnwith
1/1 [==============================] - 0s 24ms/step
we are going will be covering the following modules modules modules learnwi